import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";

const Dashboard = () => {
  const [activeTab, setActiveTab] = useState("OVERVIEW");

  const navigationItems = [
    { id: "OVERVIEW", label: "OVERVIEW", icon: "✦" },
    { id: "MY_ASSETS", label: "MY ASSETS", icon: "⊞" },
    { id: "MARKETPLACE", label: "MARKETPLACE", icon: "🏪" },
    { id: "CATEGORIES", label: "CATEGORIES", icon: "◈" },
    { id: "STAKE", label: "STAKE", icon: "⚙" },
    { id: "CONTACT", label: "CONTACT", icon: "@" },
  ];

  const stats = [
    { label: "TOTAL TOKEN SUPPLY", value: "100,000,000 PIN", icon: "?" },
    { label: "TOTAL ASSETS", value: "217", icon: "?" },
    { label: "TOTAL HASHRATE", value: "98,916,473 GH/s", icon: "?" },
    { label: "TOTAL FRACTIONS", value: "8,255", icon: "?" },
  ];

  return (
    <div className="min-h-screen bg-black text-white font-mono">
      {/* Header */}
      <header className="border-b border-gray-800 p-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 bg-primary rounded-sm flex items-center justify-center">
              <span className="text-black font-bold text-sm">⚡</span>
            </div>
            <span className="text-xl font-bold">PinLink</span>
          </div>
          <div className="text-primary text-sm">
            [0X2C7E...CEBAa]
          </div>
        </div>
      </header>

      {/* Navigation Bar */}
      <nav className="border-b border-gray-800">
        <div className="flex items-center px-6">
          {navigationItems.map((item) => (
            <button
              key={item.id}
              onClick={() => setActiveTab(item.id)}
              className={`flex items-center gap-2 px-4 py-4 text-sm transition-colors border-b-2 ${
                activeTab === item.id
                  ? "border-primary text-primary"
                  : "border-transparent text-gray-400 hover:text-white"
              }`}
            >
              <span>{item.icon}</span>
              {item.label}
            </button>
          ))}
          <div className="ml-auto">
            <span className="bg-blue-600 text-blue-100 px-2 py-1 rounded text-xs">
              🪙 NEW USDC
            </span>
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <main className="p-6">
        {activeTab === "OVERVIEW" && (
          <div className="space-y-8">
            {/* Total Generated Section */}
            <div>
              <p className="text-primary text-sm mb-2 uppercase tracking-wider">
                Total Generated by PinLink
              </p>
              <div className="text-6xl font-bold mb-2">$1,626,050</div>
              <div className="flex items-center gap-2 text-sm">
                <span>1 SPIN = $0.76 USD</span>
                <span className="flex items-center gap-1 text-primary">
                  <span className="w-2 h-2 bg-primary rounded-full"></span>
                  0.7% TODAY
                </span>
              </div>
            </div>

            <Separator className="bg-gray-800" />

            {/* Stats Grid */}
            <div className="grid grid-cols-4 gap-8">
              {stats.map((stat, index) => (
                <div key={index} className="space-y-2">
                  <div className="flex items-center gap-2 text-gray-400 text-sm uppercase tracking-wider">
                    {stat.label}
                    <span className="text-xs opacity-50">{stat.icon}</span>
                  </div>
                  <div className="text-2xl font-bold">{stat.value}</div>
                </div>
              ))}
            </div>
          </div>
        )}

        {activeTab === "MY_ASSETS" && (
          <div className="text-center py-12">
            <p className="text-gray-400">My Assets section coming soon...</p>
          </div>
        )}

        {activeTab === "MARKETPLACE" && (
          <div className="text-center py-12">
            <p className="text-gray-400">Marketplace section coming soon...</p>
          </div>
        )}

        {activeTab === "CATEGORIES" && (
          <div className="text-center py-12">
            <p className="text-gray-400">Categories section coming soon...</p>
          </div>
        )}

        {activeTab === "STAKE" && (
          <div className="text-center py-12">
            <p className="text-gray-400">Stake section coming soon...</p>
          </div>
        )}

        {activeTab === "CONTACT" && (
          <div className="text-center py-12">
            <p className="text-gray-400">Contact section coming soon...</p>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-800 p-6 mt-auto">
        <div className="flex items-center justify-between text-sm text-gray-400">
          <div className="flex items-center gap-4">
            <span>2024 PinLink -- All Rights Reserved</span>
            <span className="flex items-center gap-1">
              <span className="w-2 h-2 bg-primary rounded-full"></span>
              All Systems [running]
            </span>
          </div>
          <div className="flex items-center gap-2">
            <span>Proofed by hacken</span>
            <div className="w-6 h-6 bg-primary rounded flex items-center justify-center">
              <span className="text-black text-xs">H</span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Dashboard;